name: thuchi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # nếu cần dùng icon, nhớ có thư mục này
  assets:
    - assets/

# 👇 phần config icon phải đặt ngoài cùng (ngang cấp flutter)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
